### ISSUE TITLE
App crashes when .arobject tracking target detects the object

### ISSUE THREAD

**Issue by implicit-invocation** [NativeVision/viro#24]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: ios14.5, ios13.7
3. Version: @viro-community/react-viro@2.20.2, react-native@0.63.4
4. Device(s): iPhone7+, iPhone X, iPhone XS, iPhone 12 pro max

## Description
We used .arobject file as a ViroARTrackingTargets and ViroARObjectMarker. We only added a ViroBox inside.
If we pointed the camera somewhere else, the app kept running without problems. But as soon as we pointed the camera to the object, the app just crashed.
No specific error showed. The crash log and console showed nothing helpful. Xcode just showed EXC_BAD_ACCESS (code=1, address=0x20).

## Reproducible Demo
Just clone the [starter-kit](https://github.com/ViroCommunity/starter-kit) and follow [this documentation](https://docs.viromedia.com/docs/viroarobjectmarker)

**Comment by NS-BOBBY-C** [comment]
I've got something a little different happening with the latest version of ViroReact (2.22.0). I'm not seeing a crash, but I followed the documentation and created a sample repo. See that [here](https://github.com/NS-BOBBY-C/starter-kit/blob/b1fccf5eaa04d4603948bc1d98e4a42af6db711b/screens/issues/ARIssue24.js)

The behavior I'm seeing is the ARObject doesn't show up at all, rather than crash. Can you reproduce what I'm seeing with the latest version?

**Comment by filipenadai** [comment]
Hello guys, I've got same problem.

**Comment by robertjcolley** [comment]
closing due to no answer.
